### ISSUE TITLE
QAMR & QASRL breaks

### ISSUE THREAD

**Issue by HaokunLiu** [nyu-mll/jiant#1018]
Traceback (most recent call last):
  File "main.py", line 16, in <module>
    main(sys.argv[1:])
  File "/home/hl3236/jiant/jiant/__main__.py", line 550, in main
    pretrain_tasks, target_tasks, vocab, word_embs = build_tasks(args, cuda_device)
  File "/home/hl3236/jiant/jiant/preprocess.py", line 404, in build_tasks
    task, split, indexers, vocab, record_file, model_preprocessing_interface
  File "/home/hl3236/jiant/jiant/preprocess.py", line 142, in _index_split
    split_text = task.get_split_text(split)
  File "/home/hl3236/jiant/jiant/tasks/qa.py", line 644, in get_split_text
    return getattr(self, "%s_data" % split)
AttributeError: 'QAMRTask' object has no attribute 'train_data'

Traceback (most recent call last):
  File "main.py", line 16, in <module>
    main(sys.argv[1:])
  File "/home/hl3236/jiant/jiant/__main__.py", line 550, in main
    pretrain_tasks, target_tasks, vocab, word_embs = build_tasks(args, cuda_device)
  File "/home/hl3236/jiant/jiant/preprocess.py", line 404, in build_tasks
    task, split, indexers, vocab, record_file, model_preprocessing_interface
  File "/home/hl3236/jiant/jiant/preprocess.py", line 142, in _index_split
    split_text = task.get_split_text(split)
  File "/home/hl3236/jiant/jiant/tasks/qa.py", line 543, in get_split_text
    return getattr(self, "%s_data" % split)
AttributeError: 'QASRLTask' object has no attribute 'train_data'

@pyeres

**Comment by pyeres** [comment]
A fix has been merged into master (865cba2).
