### ISSUE TITLE
problem with running the main.py file

### ISSUE THREAD

**Issue by lovodkin93** [nyu-mll/jiant#1051]
Hey,
I'm following the instructions that are in the README file located under the directory /probing.
i did the pretraining, and tried to run the following command:
cd ${PWD%/jiant*}/jiant
python main.py --config_file jiant/config/edgeprobe/edgeprobe_cove.conf \
  -o "target_tasks=edges-spr2,exp_name=ep_cove_demo"

and got the following error:
Fatal error in main():
Traceback (most recent call last):
  File "main.py", line 16, in <module>
    main(sys.argv[1:])
  File "/cs/labs/oabend/lovodkin93/jiant_rep/jiant/jiant/__main__.py", line 550, in main
    pretrain_tasks, target_tasks, vocab, word_embs = build_tasks(args, cuda_device)
  File "/cs/labs/oabend/lovodkin93/jiant_rep/jiant/jiant/preprocess.py", line 371, in build_tasks
    word_embs = _build_embeddings(args, vocab, emb_file)
  File "/cs/labs/oabend/lovodkin93/jiant_rep/jiant/jiant/preprocess.py", line 217, in _build_embeddings
    args.word_embs_file, "r", encoding="utf-8", newline="\n", errors="ignore"
FileNotFoundError: [Errno 2] No such file or directory: 'None'
Traceback (most recent call last):
  File "main.py", line 27, in <module>
    raise e  # re-raise exception, in case debugger is attached.
  File "main.py", line 16, in <module>
    main(sys.argv[1:])
  File "/cs/labs/oabend/lovodkin93/jiant_rep/jiant/jiant/__main__.py", line 550, in main
    pretrain_tasks, target_tasks, vocab, word_embs = build_tasks(args, cuda_device)
  File "/cs/labs/oabend/lovodkin93/jiant_rep/jiant/jiant/preprocess.py", line 371, in build_tasks
    word_embs = _build_embeddings(args, vocab, emb_file)
  File "/cs/labs/oabend/lovodkin93/jiant_rep/jiant/jiant/preprocess.py", line 217, in _build_embeddings
    args.word_embs_file, "r", encoding="utf-8", newline="\n", errors="ignore"
FileNotFoundError: [Errno 2] No such file or directory: 'None'

it seems that the word_embs_file that pases in 'None' (probably null or something of the sort), but i can't seem to find to origin of that sending.
Can someone please help me with that problem?
Thanks!
@HaokunLiu

**Comment by sleepinyourhat** [comment]
One guess: IIRC, CoVe requires GloVe, and to use GloVe in jiant you need to specify a path to the GloVe embedding file (that you download yourself). That's specified here an an environment variable import, though you can override it as a config option:

https://github.com/nyu-mll/jiant/blob/master/jiant/config/defaults.conf#L278

**Comment by sleepinyourhat** [comment]
@iftenney is likely the last person to have used this config file, though things may have changed since then.

**Comment by lovodkin93** [comment]
you are right, i have indeed forgotten to update the constant.
Thank you!
