### ISSUE TITLE
Parameter parsing error with custom config.

### ISSUE THREAD

**Issue by jkamalu** [nyu-mll/jiant#1085]
> Traceback (most recent call last):
  File "jiant/main.py", line 16, in <module>
    main(sys.argv[1:])
  File "/juice/scr/scr110/scr/nlp/kamalu/task-sim/jiant/jiant/__main__.py", line 572, in main
    args, seed = initial_setup(args, cl_args)
  File "/juice/scr/scr110/scr/nlp/kamalu/task-sim/jiant/jiant/__main__.py", line 402, in initial_setup
    print_args = select_relevant_print_args(args)
  File "/juice/scr/scr110/scr/nlp/kamalu/task-sim/jiant/jiant/utils/utils.py", line 293, in select_relevant_print_args
    diff_args = Params.clone(diff_args)
  File "/juice/scr/scr110/scr/nlp/kamalu/task-sim/jiant/jiant/utils/config.py", line 41, in clone
    raise ValueError("Cannot clone from type: " + str(type(source)))
ValueError: Cannot clone from type: <class 'NoneType'>

I run main.py and jiant fails after correctly parsing the following overrides:

> Config overrides: exp_name = pretraining, run_name = sst/2020.05.13-14:21:18/train, pretrain_tasks = "sst", target_tasks="sst"

I am using a custom config file which inherits from the defaults and includes **no extra parameters.**

> include "./defaults.conf"

In particular, it's the custom config which breaks. I can still run just using command line overrides. This was working in January, but I reinstalled and cannot get past this error.

**Comment by jkamalu** [comment]
My mistake, I was using an old version of defaults.conf – closing.
