### ISSUE TITLE
Error in edgeprobe_bert

### ISSUE THREAD

**Issue by sagnik** [nyu-mll/jiant#1115]
I am trying to run a probing test on Ontonotes SRL data with BERT as the pretrained model. 

This:
```
(jiant) user:jiant$ python main.py --config_file jiant/config/edgeprobe/edgeprobe_bert.conf -o "target_tasks=edges-srl-ontonotes,exp_name=exp_bert_srl_ontonotes"
```
gives the following error:
```
Traceback (most recent call last):
  File "main.py", line 16, in <module>
    main(sys.argv[1:])
  File "/home/user/jiant/jiant/__main__.py", line 664, in main
    phase="target_train",
  File "/home/user/jiant/jiant/trainer.py", line 493, in train
    tasks, batch_size, train_params, optimizer_params, scheduler_params, phase
  File "/home/user/jiant/jiant/trainer.py", line 330, in _setup_training
    pad_dict = instance.get_padding_lengths()
  File "/home/user/anaconda3/envs/jiant/lib/python3.6/site-packages/allennlp/data/instance.py", line 81, in get_padding_lengths
    lengths[field_name] = field.get_padding_lengths()
  File "/home/user/anaconda3/envs/jiant/lib/python3.6/site-packages/allennlp/data/fields/text_field.py", line 128, in get_padding_lengths
    padding_lengths['num_tokens'] = max(num_tokens)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "main.py", line 27, in <module>
    raise e  # re-raise exception, in case debugger is attached.
  File "main.py", line 16, in <module>
    main(sys.argv[1:])
  File "/home/user/jiant/jiant/__main__.py", line 664, in main
    phase="target_train",
  File "/home/user/jiant/jiant/trainer.py", line 493, in train
    tasks, batch_size, train_params, optimizer_params, scheduler_params, phase
  File "/home/user/jiant/jiant/trainer.py", line 330, in _setup_training
    pad_dict = instance.get_padding_lengths()
  File "/home/user/anaconda3/envs/jiant/lib/python3.6/site-packages/allennlp/data/instance.py", line 81, in get_padding_lengths
    lengths[field_name] = field.get_padding_lengths()
  File "/home/user/anaconda3/envs/jiant/lib/python3.6/site-packages/allennlp/data/fields/text_field.py", line 128, in get_padding_lengths
    padding_lengths['num_tokens'] = max(num_tokens)
ValueError: max() arg is an empty sequence
```
Am I doing something stupid or you can reproduce this? I have previously run this successfully:

```
(jiant) user:jiant$ python main.py --config_file jiant/config/edgeprobe/edgeprobe_cove.conf -o "target_tasks=edges-coref-ontonotes,exp_name=ep_cove_demo_coref_ontonotes
```

**Comment by sagnik** [comment]
This is with `bert-base-uncased` if that's required.

**Comment by sleepinyourhat** [comment]
@iftenney Is this familiar?

**Comment by zphang** [comment]
*This is an automatically generated comment.*

    As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

    If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/1115.

    If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
