### ISSUE TITLE
Tokenization error for QASRL

### ISSUE THREAD

**Issue by claravania** [nyu-mll/jiant#1156]
**Describe the bug**
Error when tokenizing training data:
```
QASRLTask
  [train]: /scratch/bowman/IRT_Experiments/jiant-2/experiments/tasks/data/qasrl/train.jsonl.gz
  [val]: /scratch/bowman/IRT_Experiments/jiant-2/experiments/tasks/data/qasrl/val.jsonl.gz
  [test]: /scratch/bowman/IRT_Experiments/jiant-2/experiments/tasks/data/qasrl/test.jsonl.gz
Tokenizing:  73%|███████████████████████████████████████████████▌                 | 466735/637987 [27:43<10:10, 280.52it/s]
Traceback (most recent call last):
  File "/scratch/cv50/jiant-2/jiant/jiant/proj/main/tokenize_and_cache.py", line 214, in <module>
    main(args=RunConfiguration.run_cli_json_prepend())
  File "/scratch/cv50/jiant-2/jiant/jiant/proj/main/tokenize_and_cache.py", line 168, in main
    args=args,
  File "/scratch/cv50/jiant-2/jiant/jiant/proj/main/tokenize_and_cache.py", line 53, in chunk_and_save
    args=args,
  File "/scratch/cv50/jiant-2/jiant/jiant/proj/main/tokenize_and_cache.py", line 129, in iter_chunk_and_save
    recorder_callback=max_valid_length_recorder,
  File "/scratch/cv50/jiant-2/jiant/jiant/shared/caching.py", line 91, in iter_chunk_and_save
    for datum in data:
  File "/scratch/cv50/jiant-2/jiant/jiant/proj/main/preprocessing.py", line 145, in iter_chunk_convert_examples_to_dataset
    verbose=verbose,
  File "/scratch/cv50/jiant-2/jiant/jiant/proj/main/preprocessing.py", line 216, in iter_chunk_tokenize_and_featurize
    yield example.tokenize(tokenizer).featurize(tokenizer, feat_spec)
  File "/scratch/cv50/jiant-2/jiant/jiant/tasks/lib/templates/span_prediction.py", line 38, in tokenize
    self.answer_char_span[0], self.answer_char_span[1], inclusive=True
  File "/scratch/cv50/jiant-2/jiant/jiant/utils/retokenize.py", line 276, in project_char_to_token_span
    mat=self.source_char_idx_to_target_token_idx, start=start, end=end, inclusive=inclusive
  File "/scratch/cv50/jiant-2/jiant/jiant/utils/retokenize.py", line 192, in _project_span
    raise ValueError(f"Project {(start, end)} into empty span in target sequence")
ValueError: Project (0, 7) into empty span in target sequence
```

**To Reproduce**
```
python ${JIANT_PATH}/proj/main/tokenize_and_cache.py \
    		--task_config_path ${DATA_DIR}/configs/${TASK_NAME}_config.json \
    		--model_type ${MODEL_NAME} \
    		--model_tokenizer_path ${MODELS_DIR}/${MODEL_NAME}/tokenizer \
    		--phases train,val,test \
    		--max_seq_length 256 \
    		--do_iter \
    		--smart_truncate \
    		--output_dir ${CACHE_DIR}/${MODEL_NAME}/${TASK_NAME}
```

1. Tell use which version of `jiant` you're using: jiant2 commit 75274759808dbc0ebe9cf4e538174ba574845f7c
2. Describe the environment where you're using `jiant`, e.g, "2 P40 GPUs": 1 P40 GPU
3. Provide the experiment config artifact (e.g., `defaults.conf`)

Task config file:
```
{
  "task": "qasrl",
  "paths": {
    "train": "/scratch/bowman/IRT_Experiments/jiant-2/experiments/tasks/data/qasrl/train.jsonl.gz",
    "val": "/scratch/bowman/IRT_Experiments/jiant-2/experiments/tasks/data/qasrl/val.jsonl.gz",
    "test": "/scratch/bowman/IRT_Experiments/jiant-2/experiments/tasks/data/qasrl/test.jsonl.gz"
  },
  "name": "qasrl"
}
```

**Comment by zphang** [comment]
Was this run with a lower-case-only tokenizer? Also see: #1200  #1201

**Comment by claravania** [comment]
This is using `roberta-large`, so I think it's case-sensitive?
