### ISSUE TITLE
Download issue when using load_dataset from HF datasets

### ISSUE THREAD

**Issue by claravania** [nyu-mll/jiant#1211]
**Describe the bug**

From some tasks, it seems the download script fails when it calls `load_dataset()` function from HF `datasets`. I got the same error for `quoref`, `arc_easy`, and `arc_challenge`. Example below for `quoref`:

```
Downloading quoref
Traceback (most recent call last):
  File "jiant/jiant/scripts/download_data/runscript.py", line 97, in <module>
    main()
  File "jiant/jiant/scripts/download_data/runscript.py", line 93, in main
    args.func(args)
  File "jiant/jiant/scripts/download_data/runscript.py", line 39, in download_data_cli
    task_names=task_names, output_base_path=output_base_path,
  File "jiant/jiant/scripts/download_data/runscript.py", line 57, in download_data
    task_config_path=os.path.join(task_config_base_path, f"{task_name}_config.json"),
  File "/scratch/cv50/jiant-2/jiant/jiant/scripts/download_data/datasets/hf_datasets_tasks.py", line 180, in download_data_and_write_config
    phase_list=hf_datasets_conversion_metadata.get("phase_list"),
  File "/scratch/cv50/jiant-2/jiant/jiant/scripts/download_data/utils.py", line 28, in convert_hf_dataset_to_examples
    dataset = datasets.load_dataset(path=path, name=name, version=version)
AttributeError: module 'datasets' has no attribute 'load_dataset'
```

Might be naming conflict with `jiant/scripts/download_data/datasets/__init__.py`?

**To Reproduce**
1. Tell use which version of `jiant` you're using: c535e78f6181facc4aa5187f204a1c2cc630dd74
2. Describe the environment where you're using `jiant`, e.g, "2 P40 GPUs": 1 k80 GPU
3. Provide the experiment config artifact (e.g., `defaults.conf`)

Download command:
```
python jiant/jiant/scripts/download_data/runscript.py download --tasks $TASK_NAME --output_path experiments/tasks/ 
```

**Comment by claravania** [comment]
I double checked my installation, I can run the following successfully in my Python interpreter:

`from datasets import load_dataset`

And the issue happened when it is defined in jiant file.

**Comment by zphang** [comment]
#1213
