### ISSUE TITLE
Download issue for newsqa

### ISSUE THREAD

**Issue by claravania** [nyu-mll/jiant#1212]
**Describe the bug**

Error when downloading newsqa dataset.

```
Downloading newsqa
Traceback (most recent call last):
  File "jiant/jiant/scripts/download_data/runscript.py", line 97, in <module>
    main()
  File "jiant/jiant/scripts/download_data/runscript.py", line 93, in main
    args.func(args)
  File "jiant/jiant/scripts/download_data/runscript.py", line 39, in download_data_cli
    task_names=task_names, output_base_path=output_base_path,
  File "jiant/jiant/scripts/download_data/runscript.py", line 69, in download_data
    task_config_path=os.path.join(task_config_base_path, f"{task_name}_config.json"),
  File "/scratch/cv50/jiant-2/jiant/jiant/scripts/download_data/datasets/files_tasks.py", line 45, in download_task_data_and_write_config
    task_name=task_name, task_data_path=task_data_path, task_config_path=task_config_path
  File "/scratch/cv50/jiant-2/jiant/jiant/scripts/download_data/datasets/files_tasks.py", line 311, in download_newsqa_data_and_write_config
    "Download CNN Stories from https://cs.nyu.edu/~kcho/DMQA/ and save to " + cnn_stories_path
AssertionError: Download CNN Stories from https://cs.nyu.edu/~kcho/DMQA/ and save to experiments/tasks/data/newsqa/cnn_stories.tgz
```

**To Reproduce**
1. Tell use which version of `jiant` you're using: c535e78f6181facc4aa5187f204a1c2cc630dd74
2. Describe the environment where you're using `jiant`, e.g, "2 P40 GPUs": 1 k80 GPU
3. Provide the experiment config artifact (e.g., `defaults.conf`)

Download command:

```
python jiant/jiant/scripts/download_data/runscript.py download --tasks $TASK_NAME --output_path experiments/tasks/ 
```

**Comment by zphang** [comment]
This is a case where you need to download a file and put it in a location before the preprocessing handles the rest. (It's on Google Drive)

**Comment by claravania** [comment]
I tried downloading the required files and I can run the script successfully.
