### ISSUE TITLE
Unable to run the simple_api_fine_tuning.ipynb with Python 3.6.9

### ISSUE THREAD

**Issue by lovhag** [nyu-mll/jiant#1320]
**Describe the bug**
I tried out my installation of jiant through the "simple example" referenced by you and encountered errors already at the import stage.

What I tried to run:
```
import os

import jiant.utils.python.io as py_io
import jiant.proj.simple.runscript as simple_run
import jiant.scripts.download_data.runscript as downloader
```

The error message I received:
```
Traceback (most recent call last):

  File "/workspace/.home/.local/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-1-f1d368124d14>", line 4, in <module>
    import jiant.proj.simple.runscript as simple_run

  File "/usr/local/lib/python3.6/dist-packages/jiant/proj/simple/runscript.py", line 9, in <module>
    import jiant.proj.main.tokenize_and_cache as tokenize_and_cache

  File "/usr/local/lib/python3.6/dist-packages/jiant/proj/main/tokenize_and_cache.py", line 8, in <module>
    import jiant.tasks.evaluate as evaluate

  File "/usr/local/lib/python3.6/dist-packages/jiant/tasks/evaluate/__init__.py", line 1, in <module>
    from .core import *  # noqa: F401,F403

  File "/usr/local/lib/python3.6/dist-packages/jiant/tasks/evaluate/core.py", line 26, in <module>
    import jiant.tasks.retrieval as tasks_retrieval

  File "/usr/local/lib/python3.6/dist-packages/jiant/tasks/retrieval.py", line 18, in <module>
    from jiant.tasks.lib.edge_probing.nonterminal import NonterminalTask

  File "/usr/local/lib/python3.6/dist-packages/jiant/tasks/lib/edge_probing/nonterminal.py", line 10, in <module>
    from jiant.tasks.lib.templates import edge_probing_single_span

  File "/usr/local/lib/python3.6/dist-packages/jiant/tasks/lib/templates/edge_probing_single_span.py", line 29, in <module>
    from jiant.utils.tokenization_normalization import normalize_tokenizations

  File "/usr/local/lib/python3.6/dist-packages/jiant/utils/tokenization_normalization.py", line 16, in <module>
    from jiant.proj.main.modeling.primary import JiantTransformersModelFactory

  File "/usr/local/lib/python3.6/dist-packages/jiant/proj/main/modeling/primary.py", line 19, in <module>
    from jiant.proj.main.modeling.taskmodels import Taskmodel

  File "/usr/local/lib/python3.6/dist-packages/jiant/proj/main/modeling/taskmodels.py", line 8, in <module>
    import jiant.proj.main.modeling.heads as heads

  File "/usr/local/lib/python3.6/dist-packages/jiant/proj/main/modeling/heads.py", line 1
    from __future__ import annotations
                                      ^
SyntaxError: future feature annotations is not defined
```

**To Reproduce**
1. jiant 2.2.0 installed with pip.
2. I'm using jiant in a docker container based on the "huggingface/transformers-pytorch-gpu:4.3.3" image with a Python 3.6.9 installation. This on a Mac OS computer.
3. I used the same config as in the simple notebook example provided by you.

**Expected behavior**
Imports work flawlessly.

**Screenshots**
Not applicable.

**Additional context**
I read somewhere that future feature annotations aren't defined for Python versions <3.7.0, so it seems a bit strange to me that you try to do this import when you claim to support Python>=3.6.0? However, I'm not that well-versed in this and appreciate any support!

**Comment by sleepinyourhat** [comment]
@zphang Mind taking a look?

**Comment by zphang** [comment]
Hi, thanks for bringing this to our attention. Because of new functionality such as dataclasses and the updated import resolution logic in Python 3.7, we indeed effectively dropped support for Python 3.6. We will update the `setup.py` to reflect this.

**Comment by lovhag** [comment]
Ok! Then I suppose that settles it.
