### ISSUE TITLE
XTREME tokenize_and_cache script error

### ISSUE THREAD

**Issue by dapurv5** [nyu-mll/jiant#1330]
**Error in Running c_tokenizer_and_cache.sh script**

For the SquAD dataset, I see the following error.

```
Reading SQuAD Entries: 100%|████████████████| 669/669 [00:00<00:00, 3355.21it/s]
Tokenizing:   0%|                                       | 0/669 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/ec2-user/jiant/jiant/proj/main/tokenize_and_cache.py", line 217, in <module>
    main(args=RunConfiguration.run_cli_json_prepend())
  File "/home/ec2-user/jiant/jiant/proj/main/tokenize_and_cache.py", line 183, in main
    args=args,
  File "/home/ec2-user/jiant/jiant/proj/main/tokenize_and_cache.py", line 64, in chunk_and_save
    args=args,
  File "/home/ec2-user/jiant/jiant/proj/main/tokenize_and_cache.py", line 86, in full_chunk_and_save
    verbose=True,
  File "/home/ec2-user/jiant/jiant/proj/main/preprocessing.py", line 125, in convert_examples_to_dataset
    verbose=verbose,
  File "/home/ec2-user/jiant/jiant/proj/main/preprocessing.py", line 178, in tokenize_and_featurize
    set_type=phase,
  File "/home/ec2-user/jiant/jiant/tasks/lib/templates/squad_style/core.py", line 179, in to_feature_list
    return_token_type_ids=True,
  File "/home/ec2-user/anaconda3/envs/pytorch_latest_p37/lib/python3.7/site-packages/transformers/tokenization_utils_base.py", line 2418, in encode_plus
    **kwargs,
  File "/home/ec2-user/anaconda3/envs/pytorch_latest_p37/lib/python3.7/site-packages/transformers/tokenization_utils_fast.py", line 475, in _encode_plus
    **kwargs,
  File "/home/ec2-user/anaconda3/envs/pytorch_latest_p37/lib/python3.7/site-packages/transformers/tokenization_utils_fast.py", line 388, in _batch_encode_plus
    is_pretokenized=is_split_into_words,
TypeError: TextInputSequence must be str
```

**Running with**
Current Mainline

**Comment by dapurv5** [comment]
The problem was in the version of transformers and tokenizers library being used. Reverting to the version specified in the requirements.txt files solved the issue. Thanks !
