### ISSUE TITLE
More informative error messages for issues with stale preprocessed data files

### ISSUE THREAD

**Issue by sleepinyourhat** [nyu-mll/jiant#549]
If I try to use an old preprocessed data directory after upgrading to the current recommended version of AllenNLP, I get this:

```
Traceback (most recent call last):
  File "main.py", line 395, in <module>
    main(sys.argv[1:])
  File "main.py", line 261, in main
    args.shared_optimizer, args.load_model, phase="main")
  File "/Users/Bowman/Drive/JSALT/jiant/src/trainer.py", line 440, in train
    tasks, batch_size, train_params, optimizer_params, scheduler_params, phase)
  File "/Users/Bowman/Drive/JSALT/jiant/src/trainer.py", line 274, in _setup_training
    pad_dict = instance.get_padding_lengths()
  File "/Users/Bowman/anaconda3/envs/jiant/lib/python3.6/site-packages/allennlp/data/instance.py", line 81, in get_padding_lengths
    lengths[field_name] = field.get_padding_lengths()
  File "/Users/Bowman/anaconda3/envs/jiant/lib/python3.6/site-packages/allennlp/data/fields/text_field.py", line 94, in get_padding_lengths
    for indexed_tokens_key in self._indexer_name_to_indexed_token[indexer_name]:
AttributeError: 'TextField' object has no attribute '_indexer_name_to_indexed_token'
```
Command:

` python main.py --config config/demo.conf`

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/549.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
