### ISSUE TITLE
demo.conf is broken at head on cpu.

### ISSUE THREAD

**Issue by sleepinyourhat** [nyu-mll/jiant#642]
`python main.py --config config/demo.conf`

yields

```
05/02/2019 18:11:51 - INFO - root -   Beginning training. Stopping metric: sts-b_corr
05/02/2019 18:11:52 - ERROR - root -   Fatal error in main():
Traceback (most recent call last):
  File "main.py", line 545, in <module>
    main(sys.argv[1:])
  File "main.py", line 477, in main
    phase="target_train",
  File "/Users/Bowman/Drive/JSALT/jiant/src/trainer.py", line 572, in train
    output_dict = self._forward(batch, task=task)
  File "/Users/Bowman/Drive/JSALT/jiant/src/trainer.py", line 995, in _forward
    model_out = self._model.forward(task, tensor_batch)
  File "/Users/Bowman/Drive/JSALT/jiant/src/models.py", line 908, in forward
    out = self._pair_sentence_forward(batch, task, predict)
  File "/Users/Bowman/Drive/JSALT/jiant/src/models.py", line 1104, in _pair_sentence_forward
    logits.data.cpu().numpy(), labels.data.cpu().numpy(), tagmask=tagmask
  File "/Users/Bowman/Drive/JSALT/jiant/src/tasks/tasks.py", line 258, in update_metrics
    logits, labels = logits.detach(), labels.detach()
AttributeError: 'numpy.ndarray' object has no attribute 'detach'
Traceback (most recent call last):
  File "main.py", line 556, in <module>
    raise e  # re-raise exception, in case debugger is attached.
  File "main.py", line 545, in <module>
    main(sys.argv[1:])
  File "main.py", line 477, in main
    phase="target_train",
  File "/Users/Bowman/Drive/JSALT/jiant/src/trainer.py", line 572, in train
    output_dict = self._forward(batch, task=task)
  File "/Users/Bowman/Drive/JSALT/jiant/src/trainer.py", line 995, in _forward
    model_out = self._model.forward(task, tensor_batch)
  File "/Users/Bowman/Drive/JSALT/jiant/src/models.py", line 908, in forward
    out = self._pair_sentence_forward(batch, task, predict)
  File "/Users/Bowman/Drive/JSALT/jiant/src/models.py", line 1104, in _pair_sentence_forward
    logits.data.cpu().numpy(), labels.data.cpu().numpy(), tagmask=tagmask
  File "/Users/Bowman/Drive/JSALT/jiant/src/tasks/tasks.py", line 258, in update_metrics
    logits, labels = logits.detach(), labels.detach()
AttributeError: 'numpy.ndarray' object has no attribute 'detach'
```

**Comment by W4ngatang** [comment]
Closed with #644
