### ISSUE TITLE
WSC loading is broken

### ISSUE THREAD

**Issue by sleepinyourhat** [nyu-mll/jiant#712]
`
06/20 09:21:34 PM: 	Creating task winograd-coreference from scratch.
06/20 09:21:34 PM: Fatal error in main():
Traceback (most recent call last):
  File "main.py", line 556, in <module>
    main(sys.argv[1:])
  File "main.py", line 381, in main
    pretrain_tasks, target_tasks, vocab, word_embs = build_tasks(args)
  File "/home/srbowman/jiant-pub/src/preprocess.py", line 282, in build_tasks
    tasks, pretrain_task_names, target_task_names = get_tasks(args)
  File "/home/srbowman/jiant-pub/src/preprocess.py", line 466, in get_tasks
    task = _get_task(name, args, data_path=data_path, scratch_path=scratch_path)
  File "/home/srbowman/jiant-pub/src/preprocess.py", line 423, in _get_task
    task.load_data()
  File "/home/srbowman/jiant-pub/src/tasks/tasks.py", line 2534, in load_data
    iters_by_split[split] = load_span_data(self.tokenizer_name, filename)
  File "/home/srbowman/jiant-pub/src/utils/data_loaders.py", line 39, in load_span_data
    rows = pd.read_json(file_name, lines=True)
  File "/home/srbowman/.conda/envs/jiant/lib/python3.6/site-packages/pandas/io/json/json.py", line 422, in read_json
    result = json_reader.read()
  File "/home/srbowman/.conda/envs/jiant/lib/python3.6/site-packages/pandas/io/json/json.py", line 526, in read
    self._combine_lines(data.split('\n'))
  File "/home/srbowman/.conda/envs/jiant/lib/python3.6/site-packages/pandas/io/json/json.py", line 546, in _get_object_parser
    obj = FrameParser(json, **kwargs).parse()
  File "/home/srbowman/.conda/envs/jiant/lib/python3.6/site-packages/pandas/io/json/json.py", line 638, in parse
    self._parse_no_numpy()
  File "/home/srbowman/.conda/envs/jiant/lib/python3.6/site-packages/pandas/io/json/json.py", line 853, in _parse_no_numpy
    loads(json, precise_float=self.precise_float), dtype=None)
ValueError: Expected object or value
`

**Comment by pruksmhc** [comment]
Addressed here: https://github.com/nyu-mll/jiant/commit/298e961b89a960dd924768a06114d4a76182c2b7
