### ISSUE TITLE
write_preds = test broken for MNLI

### ISSUE THREAD

**Issue by sleepinyourhat** [nyu-mll/jiant#729]
MWE:
```
python main.py --config config/demo.conf --overrides "do_pretrain = 0, pretrain_tasks = mnli, target_tasks = mnli, write_preds = test, allow_untrained_encoder_parameters = 1, mnli={max_vals=1, val_interval = 1}, run_name = mnli-mwe"
```
Error:
```
Traceback (most recent call last):
  File "main.py", line 564, in <module>
    raise e  # re-raise exception, in case debugger is attached.
  File "main.py", line 553, in <module>
    main(sys.argv[1:])
  File "main.py", line 546, in main
    evaluate_and_write(args, model, target_tasks, splits_to_write)
  File "main.py", line 287, in evaluate_and_write
    tasks, te_preds, args.run_dir, "test", strict_glue_format=args.write_strict_glue_format
  File "/nfs/jiant/home/srbowman/jiant/src/evaluate.py", line 160, in write_preds
    _write_glue_preds(task.name, preds_df, pred_dir, split_name, strict_glue_format=strict)
  File "/nfs/jiant/home/srbowman/jiant/src/evaluate.py", line 504, in _write_glue_preds
    assert len(preds_df) == 20747, "Missing predictions for MNLI!"
AssertionError: Missing predictions for MNLI!
```

This seems to only happen for the test set, and the issue has likely appeared by the time the task is done loading. Evidence: `06/24 02:24:50 PM:     Task 'mnli': |train|=392662 |val|=19647 |test|=20744`

**Comment by pruksmhc** [comment]
This is because there are 3 NLI examples in MNLI that have NaNs for one of the two sentences

**Comment by sleepinyourhat** [comment]
NaNs?

**Comment by sleepinyourhat** [comment]
Relevant: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html

**Comment by sleepinyourhat** [comment]
The literal strings in the data are "n/a", which are genuine (short) sentences that annotators produced and labels. We just need to make sure they load as strings, not NaNs.

**Comment by sleepinyourhat** [comment]
Things like this are why we switched away from tsv for SuperGLUE...

**Comment by sleepinyourhat** [comment]
#734
