### ISSUE TITLE
PRPN and ON-LSTM broken at head

### ISSUE THREAD

**Issue by sleepinyourhat** [nyu-mll/jiant#754]
@anhad13, @phu-pmh - Would either of you mind taking a look? Someone will need to fix this ASAP (ideally this week) or else we'll have to delete it for the 1.0 release, and it'll probably be easier for you than for us if you spot an obvious issue.

It may be as simple as adding the necessary parameters to defaults.conf.

```
python main.py --config config/demo.conf --overrides "run_name = prpn, sent_enc = prpn"
```

```
06/26 01:57:20 PM: Fatal error in main():
Traceback (most recent call last):
  File "main.py", line 599, in <module>
    main(sys.argv[1:])
  File "main.py", line 422, in main
    model = build_model(args, vocab, word_embs, tasks)
  File "/nfs/jiant/home/srbowman/jiant/src/models.py", line 268, in build_model
    args, vocab, d_emb, tasks, embedder, cove_layer
  File "/nfs/jiant/home/srbowman/jiant/src/models.py", line 137, in build_sent_encoder
    args.n_slots,
AttributeError: 'Params' object has no attribute 'n_slots'
Traceback (most recent call last):
  File "main.py", line 610, in <module>
    raise e  # re-raise exception, in case debugger is attached.
  File "main.py", line 599, in <module>
    main(sys.argv[1:])
  File "main.py", line 422, in main
    model = build_model(args, vocab, word_embs, tasks)
  File "/nfs/jiant/home/srbowman/jiant/src/models.py", line 268, in build_model
    args, vocab, d_emb, tasks, embedder, cove_layer
  File "/nfs/jiant/home/srbowman/jiant/src/models.py", line 137, in build_sent_encoder
    args.n_slots,
AttributeError: 'Params' object has no attribute 'n_slots'
```

**Comment by sleepinyourhat** [comment]
Similar-looking issue for ON-LSTM. Every feature needs to be testable from defaults.conf/demo.conf.

```
python main.py --config config/demo.conf --overrides "run_name = prpn, sent_enc = onlstm"
```
```
06/26 02:00:04 PM: Building model...
06/26 02:00:04 PM: 	Training word embeddings from scratch.
06/26 02:00:04 PM: 	Not using character embeddings!
06/26 02:00:04 PM: Fatal error in main():
Traceback (most recent call last):
  File "main.py", line 599, in <module>
    main(sys.argv[1:])
  File "main.py", line 422, in main
    model = build_model(args, vocab, word_embs, tasks)
  File "/nfs/jiant/home/srbowman/jiant/src/models.py", line 268, in build_model
    args, vocab, d_emb, tasks, embedder, cove_layer
  File "/nfs/jiant/home/srbowman/jiant/src/models.py", line 110, in build_sent_encoder
    args.chunk_size,
AttributeError: 'Params' object has no attribute 'chunk_size'
Traceback (most recent call last):
  File "main.py", line 610, in <module>
    raise e  # re-raise exception, in case debugger is attached.
  File "main.py", line 599, in <module>
    main(sys.argv[1:])
  File "main.py", line 422, in main
    model = build_model(args, vocab, word_embs, tasks)
  File "/nfs/jiant/home/srbowman/jiant/src/models.py", line 268, in build_model
    args, vocab, d_emb, tasks, embedder, cove_layer
  File "/nfs/jiant/home/srbowman/jiant/src/models.py", line 110, in build_sent_encoder
    args.chunk_size,
AttributeError: 'Params' object has no attribute 'chunk_size'
-bash: Better: command not found
```

**Comment by anhad13** [comment]
I will fix this within the week.

**Comment by phu-pmh** [comment]
Will work on it

**Comment by sleepinyourhat** [comment]
Thanks! Should be simple, I hope.
