### ISSUE TITLE
WSC is loading is broken again

### ISSUE THREAD

**Issue by sleepinyourhat** [nyu-mll/jiant#773]
```
rm -r $JIANT_PROJECT_PREFIX/jiant-demo;  python main.py --config config/demo.conf --overrides "target_tasks = winograd-coreference"
```
...yields an unhelpful error that we need to fix.
```
Traceback (most recent call last):
  File "main.py", line 566, in <module>
    main(sys.argv[1:])
  File "main.py", line 534, in main
    phase="target_train",
  File "/Users/srbowman/jiant/src/trainer.py", line 594, in train
    output_dict = self._forward(batch, task=task)
  File "/Users/srbowman/jiant/src/trainer.py", line 1035, in _forward
    model_out = self._model.forward(task, tensor_batch)
  File "/Users/srbowman/jiant/src/models.py", line 830, in forward
    out = self._span_forward(batch, task, predict)
  File "/Users/srbowman/jiant/src/models.py", line 917, in _span_forward
    out = module.forward(batch, sent_embs, sent_mask, task, predict)
  File "/Users/srbowman/jiant/src/modules/span_modules.py", line 134, in forward
    out["loss"] = self.compute_loss(logits, batch["labels"].squeeze(dim=1), task)
  File "/Users/srbowman/jiant/src/modules/span_modules.py", line 184, in compute_loss
    raise ValueError("Unsupported loss type '%s' " "for edge probing." % self.loss_type)
ValueError: Unsupported loss type '' for edge probing.
Traceback (most recent call last):
  File "main.py", line 577, in <module>
    raise e  # re-raise exception, in case debugger is attached.
  File "main.py", line 566, in <module>
    main(sys.argv[1:])
  File "main.py", line 534, in main
    phase="target_train",
  File "/Users/srbowman/jiant/src/trainer.py", line 594, in train
    output_dict = self._forward(batch, task=task)
  File "/Users/srbowman/jiant/src/trainer.py", line 1035, in _forward
    model_out = self._model.forward(task, tensor_batch)
  File "/Users/srbowman/jiant/src/models.py", line 830, in forward
    out = self._span_forward(batch, task, predict)
  File "/Users/srbowman/jiant/src/models.py", line 917, in _span_forward
    out = module.forward(batch, sent_embs, sent_mask, task, predict)
  File "/Users/srbowman/jiant/src/modules/span_modules.py", line 134, in forward
    out["loss"] = self.compute_loss(logits, batch["labels"].squeeze(dim=1), task)
  File "/Users/srbowman/jiant/src/modules/span_modules.py", line 184, in compute_loss
    raise ValueError("Unsupported loss type '%s' " "for edge probing." % self.loss_type)
ValueError: Unsupported loss type '' for edge probing.
```

Or, following the superglue-bert setup:

```
rm -r $JIANT_PROJECT_PREFIX/jiant-demo;  python main.py --config config/demo.conf --overrides "target_tasks = winograd-coreference, classifier_loss_fn = softmax, classifier_span_pooling = attn"
```
...yields a CUDA error on CPU, when everything else runs fine without CUDA.
```
06/27 05:11:20 PM: Beginning training with stopping criteria based on metric: winograd-coreference_acc
06/27 05:11:20 PM: Fatal error in main():
Traceback (most recent call last):
  File "main.py", line 566, in <module>
    main(sys.argv[1:])
  File "main.py", line 534, in main
    phase="target_train",
  File "/Users/srbowman/jiant/src/trainer.py", line 594, in train
    output_dict = self._forward(batch, task=task)
  File "/Users/srbowman/jiant/src/trainer.py", line 1035, in _forward
    model_out = self._model.forward(task, tensor_batch)
  File "/Users/srbowman/jiant/src/models.py", line 830, in forward
    out = self._span_forward(batch, task, predict)
  File "/Users/srbowman/jiant/src/models.py", line 917, in _span_forward
    out = module.forward(batch, sent_embs, sent_mask, task, predict)
  File "/Users/srbowman/jiant/src/modules/span_modules.py", line 137, in forward
    task.update_metrics(predictions, batch["labels"].squeeze(dim=1), tagmask=tagmask)
  File "/Users/srbowman/jiant/src/tasks/tasks.py", line 2554, in update_metrics
    binary_preds = make_one_hot(logits, depth=2)
  File "/Users/srbowman/jiant/src/tasks/tasks.py", line 2551, in make_one_hot
    ones = torch.sparse.torch.eye(depth).cuda()
  File "/Users/srbowman/miniconda3/envs/jiant/lib/python3.6/site-packages/torch/cuda/__init__.py", line 162, in _lazy_init
    _check_driver()
  File "/Users/srbowman/miniconda3/envs/jiant/lib/python3.6/site-packages/torch/cuda/__init__.py", line 75, in _check_driver
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
Traceback (most recent call last):
  File "main.py", line 577, in <module>
    raise e  # re-raise exception, in case debugger is attached.
  File "main.py", line 566, in <module>
    main(sys.argv[1:])
  File "main.py", line 534, in main
    phase="target_train",
  File "/Users/srbowman/jiant/src/trainer.py", line 594, in train
    output_dict = self._forward(batch, task=task)
  File "/Users/srbowman/jiant/src/trainer.py", line 1035, in _forward
    model_out = self._model.forward(task, tensor_batch)
  File "/Users/srbowman/jiant/src/models.py", line 830, in forward
    out = self._span_forward(batch, task, predict)
  File "/Users/srbowman/jiant/src/models.py", line 917, in _span_forward
    out = module.forward(batch, sent_embs, sent_mask, task, predict)
  File "/Users/srbowman/jiant/src/modules/span_modules.py", line 137, in forward
    task.update_metrics(predictions, batch["labels"].squeeze(dim=1), tagmask=tagmask)
  File "/Users/srbowman/jiant/src/tasks/tasks.py", line 2554, in update_metrics
    binary_preds = make_one_hot(logits, depth=2)
  File "/Users/srbowman/jiant/src/tasks/tasks.py", line 2551, in make_one_hot
    ones = torch.sparse.torch.eye(depth).cuda()
  File "/Users/srbowman/miniconda3/envs/jiant/lib/python3.6/site-packages/torch/cuda/__init__.py", line 162, in _lazy_init
    _check_driver()
  File "/Users/srbowman/miniconda3/envs/jiant/lib/python3.6/site-packages/torch/cuda/__init__.py", line 75, in _check_driver
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
```

**Comment by sleepinyourhat** [comment]
(The second command works on GPU, but we need to support local debugging without CUDA.)

**Comment by sleepinyourhat** [comment]
I'll look for a fix for the first half.

**Comment by iftenney** [comment]
I haven't followed the refactors very closely, but it seems like it would be safe to change the error message to no longer refer to edge probing. For `span_modules.py`, change lines 165 and 184 to:
```python
            raise ValueError("Unsupported loss type '%s' " "for span classifier." % self.loss_type)
```

**Comment by iftenney** [comment]
Also, this looks like a typo: https://github.com/nyu-mll/jiant/blob/master/src/modules/span_modules.py#L17
