### ISSUE TITLE
mnli error: sent, mask = self.sent_encoder(batch["inputs"], task) KeyError: 'inputs'

### ISSUE THREAD

**Issue by ppriyank** [nyu-mll/jiant#919]
For the rte++  in superglue baseline script and tasks involving mnli with BERT: I get the following error 

```09/27 05:59:03 PM: Fatal error in main():
Traceback (most recent call last):
  File "main.py", line 16, in <module>
    main(sys.argv[1:])
  File "jiant/jiant/__main__.py", line 540, in main
    phase="pretrain",
  File "jiant/jiant/trainer.py", line 598, in train
    output_dict = self._forward(batch, task=task)
  File "jiant/jiant/trainer.py", line 1038, in _forward
    model_out = self._model.forward(task, tensor_batch)
  File "jiant/jiant/models.py", line 835, in forward
    out = self._pair_sentence_forward(batch, task, predict)
  File "jiant/jiant/models.py", line 960, in _pair_sentence_forward
    sent, mask = self.sent_encoder(batch["inputs"], task)
KeyError: 'inputs'
Traceback (most recent call last):
  File "main.py", line 27, in <module>
    raise e  # re-raise exception, in case debugger is attached.
  File "main.py", line 16, in <module>
    main(sys.argv[1:])
  File "jiant/jiant/__main__.py", line 540, in main
    phase="pretrain",
  File "jiant/jiant/trainer.py", line 598, in train
    output_dict = self._forward(batch, task=task)
  File "jiant/jiant/trainer.py", line 1038, in _forward
    model_out = self._model.forward(task, tensor_batch)
  File "jiant/jiant/models.py", line 835, in forward
    out = self._pair_sentence_forward(batch, task, predict)
  File "jiant/jiant/models.py", line 960, in _pair_sentence_forward
    sent, mask = self.sent_encoder(batch["inputs"], task)
KeyError: 'inputs'
```

Does any encounter the same problem or know the what I might be doing wrong?

**Comment by HaokunLiu** [comment]
I run it from my environment, it seems to train normally. Maybe you can try to override the exp_name with an unused name (or delete everything under /bert-large-cased/preproc in your $JIANT_PROJECT_PREFIX .

My guess is that you already have a preprocessed mnli dataset when running a non-bert model in your exp directory, which does not concatenate the two sentences like bert.

**Comment by ppriyank** [comment]
The second explanation worked for me, thanks a lot :D

**Comment by adhithyaarun** [comment]
I seem to be facing the same issue while using `bert-base-uncased` for GLUE tasks and `wiki103-classif` as pretraining task. I have tried the above suggestions, but neither of them seem to work. The configuration file is as follows:
```
include "defaults.conf"

exp_name = bert-glue
run_name = bert-run-1

random_seed = 42

cuda = auto

load_model = 0
reload_tasks = 0
reload_indexing = 0
reload_vocab = 0

pretrain_tasks = wiki103-classif
target_tasks = glue

target_task_training = 0
patience = 20

write_strict_glue_format = 1

pretrain_tasks = wiki103-classif
target_tasks = glue

do_pretrain = 1
do_target_task_training = 1
do_full_eval = 1

input_module = bert-base-uncased
transfer_paradigm = frozen
classifier = log_reg
optimizer = bert_adam
lr = 0.00001
sent_enc = none
sep_embs_for_skip = 1
max_seq_len = 256
dropout = 0.1

batch_size = 4
max_epochs = 10
write_strict_glue_format = 1
```
NOTE: `torch==1.0.1`
Any other possible fixes?
